services:
  socketbase:
    image: socketbase/socketbase:latest
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config.yaml:/app/config.yaml
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=socketbase
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
